defmodule TermelixWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :termelix
  # Report request-processing crashes to Sentry (no-op while no DSN is configured).
  use Sentry.PlugCapture

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_termelix_key",
    signing_salt: "rtfssBDI",
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Must stay first: every later plug (and every controller) reads `conn.remote_ip` and
  # `conn.scheme` expecting them to reflect the real client, and `ForceSSL` must not decide on a
  # scheme that has not been trust-checked. `ForceSSL` replaces Phoenix's compile-time
  # `:force_ssl` option, which Phoenix would otherwise install ahead of both.
  plug TermelixWeb.Plugs.TrustedProxy
  plug TermelixWeb.Plugs.ForceSSL

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # Fingerprinted Vite bundles are immutable: cache them for a year. Must come before the
  # general SPA plug so /assets responses get these headers instead of plain etags.
  plug Plug.Static,
    at: "/",
    from: {:termelix, "priv/static/spa"},
    # Both, and brotli first: `Plug.Static` tries the encodings in order and brotli is ~15%
    # smaller than gzip on this kind of payload. Both are produced at image build time
    # (`docker/Dockerfile`), so neither costs anything per request — and a client that accepts
    # neither still gets the original file.
    brotli: not code_reloading?,
    gzip: not code_reloading?,
    only: ~w(assets),
    headers: %{"cache-control" => "public, max-age=31536000, immutable"},
    raise_on_missing_only: code_reloading?

  # Serve the built React SPA (priv/static/spa) at the root origin. Its index.html
  # references ./assets/*, so assets must live at /assets. Unmatched GET routes fall
  # through to the SPA fallback controller (client-side routing).
  plug Plug.Static,
    at: "/",
    from: {:termelix, "priv/static/spa"},
    brotli: not code_reloading?,
    gzip: not code_reloading?,
    only: ~w(fonts icons images favicon.ico full-icon.png icon-mac.png icon.icns
             icon.ico icon.png icon.svg manifest.json pdf.worker.min.js sw.js robots.txt),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :termelix
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  # Sentry's defaults only know "password"/"passwd"/"secret"
  # (deps/sentry/lib/sentry/scrubber.ex:78), which misses every secret name this app uses:
  # `key`, `keyPassword`, `sudoPassword`, `client_secret`. `Termelix.Redaction` owns that list.
  #
  # BOTH scrubbers are needed. The body one alone filtered `?token=`/`?ticket=` out of `data`
  # and then let Sentry report them verbatim in `request.url` — and this app deliberately puts
  # live credentials there, because the in-WebView terminal socket cannot set headers. Sentry
  # derives `query_string` from the same URL, so the url_scrubber covers both fields.
  plug Sentry.PlugContext,
    body_scrubber: {Termelix.Redaction, :scrub_body, []},
    url_scrubber: {Termelix.Redaction, :scrub_url, []},
    header_scrubber: {Termelix.Redaction, :scrub_headers, []}

  plug Plug.Head
  plug :secure_browser_headers

  # Function plug wrapper: `put_secure_browser_headers/2` lives in Phoenix.Controller and
  # endpoints don't import it.
  defp secure_browser_headers(conn, opts),
    do: Phoenix.Controller.put_secure_browser_headers(conn, opts)

  plug Plug.Session, @session_options

  # CORS runs HERE, not only in the router's `:api` pipeline, because a pipeline is reached
  # only once a route MATCHES. A browser preflight is an `OPTIONS` request and the router
  # declares no `options` routes, so preflight never reached the plug — it 404'd. That was
  # invisible while every cross-origin call was a "simple request", and stops being invisible
  # the moment one carries a custom header: `x-reauth-password` on the admin export is exactly
  # that, and would fail from the two non-canonical origins ALLOWED_ORIGINS exists to permit.
  # The plug is a no-op without an `Origin` header, so same-origin and native clients are
  # unaffected. It stays in the `:api` pipeline too — harmless, and it keeps the router honest
  # about the fact that these routes are CORS-governed.
  plug TermelixWeb.Plugs.Cors

  plug TermelixWeb.Router
end
