defmodule Termelix.Schema.ApiKey do
  @moduledoc """
  The `api_keys` table: a scoped, revocable credential for a non-human caller.

  Struct keys are camelCase like every other schema here (the wire shape the SPA and the CLI
  share); the columns are snake_case. `keyHash` is SHA-256 of the token — the token itself is
  never stored, and `Termelix.ApiKeys.create/2` is the only place it exists.
  """
  use Ecto.Schema

  import Ecto.Changeset

  @type t :: %__MODULE__{}

  # TEXT primary key, generated by `Termelix.Id` — the shape the table has shipped with since
  # the Node port. Not changed to an autoincrement integer: renaming or retyping a column of a
  # table that already exists in every install buys nothing here.
  @primary_key {:id, :string, autogenerate: false}

  schema "api_keys" do
    field :userId, :string, source: :user_id
    field :name, :string
    field :keyHash, :string, source: :token_hash
    field :keyPrefix, :string, source: :token_prefix
    # JSON arrays — SQLite has no array type, and this app already stores lists this way.
    field :scopes, :string
    field :hostIds, :string, source: :host_ids
    field :expiresAt, :string, source: :expires_at
    field :lastUsedAt, :string, source: :last_used_at
    field :createdAt, :string, source: :created_at
    field :isActive, :boolean, source: :is_active, default: true
  end

  @doc false
  def changeset(key, attrs) do
    key
    |> cast(attrs, [
      :userId,
      :name,
      :keyHash,
      :keyPrefix,
      :scopes,
      :hostIds,
      :expiresAt,
      :lastUsedAt,
      :createdAt,
      :isActive
    ])
    |> validate_required([:userId, :name, :keyHash, :keyPrefix])
    |> unique_constraint(:keyHash)
  end
end
