defmodule Termelix.SSH.KeyDecode do
  @moduledoc """
  Turns a stored SSH private key into the term OTP's `:ssh` expects, and names the failure
  when it cannot.

  Three formats reach us from the host and credential editors, and `:public_key.pem_decode/1`
  alone handles only the first:

    * **PEM / PKCS#1 / PKCS#8** (`BEGIN RSA PRIVATE KEY`, `BEGIN PRIVATE KEY`, …) — decoded
      by `:public_key`, with or without a passphrase.
    * **OpenSSH v1, unencrypted** (`BEGIN OPENSSH PRIVATE KEY`) — the default `ssh-keygen`
      output since OpenSSH 7.8 (2018), and the only form an ed25519 key takes unless it is
      explicitly exported as PKCS#8. `pem_decode/1` returns one
      `{{:no_asn1, :new_openssh}, der, :not_encrypted}` entry for it (`pubkey_pem.erl:293`)
      and `:public_key.pem_entry_decode/1` has no clause that accepts it — its guard demands
      an *atom* asn1 type (`public_key.erl:483`) — so it raises `function_clause`. Those keys
      go through `:ssh_file.decode/2` instead.
    * **OpenSSH v1, passphrase-protected** — *not supported*. OTP refuses the bcrypt KDF
      outright (`ssh_file.erl:1401`: `error({decryption, {not_supported, bcrypt}})`) and
      `:ssh_file.decode/2` has no passphrase-carrying form at all, so the refusal is
      swallowed by `decode_ssh_file/4`'s catch-all (`ssh_file.erl:1160-1162`) and looks
      exactly like a corrupt key. We therefore detect the case from the key's own header and
      return `:encrypted_openssh_key`, whose message tells the operator to convert the key
      with `ssh-keygen -p -m PEM`. Supporting these needs bcrypt_pbkdf plus a manual
      aes256-ctr/gcm unwrap — a separate item, deliberately out of scope here.

  ## Two traps in `:ssh_file.decode/2`

  It returns a **list** of `{key, attributes}` pairs holding both the public *and* the private
  key of every pair in the file (`ssh_file.erl:1177-1181`), so the private entry must be
  selected by shape; `hd/1` only happens to hit the private key of a one-key file because the
  accumulator is reversed on the way out. And OTP documents the `openssh_key_v1` format as
  **experimental** (`ssh_file.erl:445`, `ssh_file.erl:254-263`), so every branch here is
  pinned by tests over keys generated by the real `ssh-keygen` rather than by fixtures.

  Nothing in this module logs, inspects or returns key material: failures are atoms and
  `message/1` renders them without ever touching the key.
  """

  @typedoc """
  Why a key could not be used. `:passphrase_required` and `:key_decrypt_failed` are about the
  *passphrase*, everything else about the key itself — see `check_format/1`, which only ever
  reports the latter.
  """
  @type reason ::
          :no_key
          | :unsupported_key_format
          | :public_key_not_private
          | :no_private_key
          | :encrypted_openssh_key
          | :passphrase_required
          | :key_decrypt_failed
          | :key_decode_failed

  @openssh_begin "-----BEGIN OPENSSH PRIVATE KEY-----"
  @openssh_end "-----END OPENSSH PRIVATE KEY-----"

  # Record tags `:ssh_message.ssh2_privkey_decode2/1` can produce (ssh_message.erl:782-836).
  # ed25519 and ed448 arrive as `ECPrivateKey` with a namedCurve parameter, not as a type of
  # their own, so this list is exhaustive for the openssh_key_v1 reader as of ssh-6.0.2.
  @private_key_records [:RSAPrivateKey, :DSAPrivateKey, :ECPrivateKey]

  # PEM entry types that carry a private key. `pem_decode/1` also yields public keys,
  # certificates and `EcpkParameters` — `openssl ecparam -genkey` writes an EC PARAMETERS
  # block *before* the key — which is why the entry is searched for rather than taken with
  # `hd/1`. PKCS#8 (`PrivateKeyInfo`) is unwrapped to the same records above by
  # `public_key:der_priv_key_decode/1`.
  @private_pem_types [:RSAPrivateKey, :DSAPrivateKey, :ECPrivateKey, :PrivateKeyInfo]

  # A pasted `.pub` line is the single most common wrong paste; recognising it turns a
  # "key unusable" into "that is the public half".
  @public_key_prefixes [
    "ssh-rsa",
    "ssh-ed25519",
    "ssh-ed448",
    "ssh-dss",
    "ecdsa-sha2-",
    "sk-ssh-",
    "sk-ecdsa-"
  ]

  @doc """
  Decode `pem` into a private key term usable as an `:ssh` client key.

  `passphrase` is used only for encrypted *PEM* keys (traditional `Proc-Type: 4,ENCRYPTED`
  and PKCS#8 `ENCRYPTED PRIVATE KEY` alike); OpenSSH-native keys either need no passphrase or
  are rejected outright, per the moduledoc.
  """
  @spec decode(binary() | nil, binary() | nil) :: {:ok, tuple()} | {:error, reason()}
  def decode(nil, _passphrase), do: {:error, :no_key}

  def decode(pem, passphrase) when is_binary(pem) do
    case classify(pem) do
      {:openssh_v1, key} -> decode_openssh_v1(key)
      {:pem, key} -> decode_pem(key, passphrase)
      {:error, reason} -> {:error, reason}
    end
  end

  def decode(_pem, _passphrase), do: {:error, :unsupported_key_format}

  @doc """
  Format-only check on a stored key, for write-time validation.

  Deliberately narrower than `decode/2`: it answers "can this key ever decode?", not "does it
  decode right now". A passphrase-protected *PEM* key passes — its passphrase is a separate
  stored column that the caller may be about to set or may already hold — while a
  passphrase-protected *OpenSSH* key fails, because no passphrase will ever open it here.
  Takes no passphrase at all, so no secret can reach this path.
  """
  @spec check_format(binary() | nil) :: :ok | {:error, reason()}
  def check_format(nil), do: {:error, :no_key}

  def check_format(pem) when is_binary(pem) do
    case classify(pem) do
      {:openssh_v1, key} -> key |> decode_openssh_v1() |> drop_key()
      {:pem, key} -> key |> check_pem_format() |> drop_key()
      {:error, reason} -> {:error, reason}
    end
  end

  def check_format(_pem), do: {:error, :unsupported_key_format}

  @doc """
  Operator-facing explanation for a `t:reason/0`. Contains no key material, so it is safe to
  return over the API and to log.
  """
  @spec message(reason()) :: String.t()
  def message(:no_key), do: "no private key was provided"

  def message(:unsupported_key_format),
    do:
      "unrecognised private key format — expected a PEM block such as " <>
        "\"-----BEGIN OPENSSH PRIVATE KEY-----\" or \"-----BEGIN RSA PRIVATE KEY-----\""

  def message(:public_key_not_private),
    do: "this is a public key (.pub); paste the matching private key instead"

  def message(:no_private_key),
    do: "the PEM block contains no private key (only a public key, certificate or parameters)"

  def message(:encrypted_openssh_key),
    do:
      "passphrase-protected OpenSSH keys are not supported yet — convert the key with " <>
        "\"ssh-keygen -p -m PEM -f <keyfile>\" (OTP cannot decrypt the bcrypt KDF)"

  def message(:passphrase_required),
    do: "this private key is passphrase-protected; a key password is required"

  def message(:key_decrypt_failed),
    do: "the private key could not be decrypted — wrong key password, or the key is damaged"

  def message(:key_decode_failed), do: "the private key could not be parsed"

  # `pem` is trimmed once here so every branch below sees armour at a line start; a leading
  # blank line makes `ssh_file`'s line-oriented reader miss the BEGIN marker entirely
  # (ssh_file.erl:1320).
  defp classify(pem) do
    key = String.trim(pem)

    cond do
      key == "" -> {:error, :no_key}
      String.contains?(key, @openssh_begin) -> {:openssh_v1, key}
      String.contains?(key, "-----BEGIN ") -> {:pem, key}
      String.starts_with?(key, @public_key_prefixes) -> {:error, :public_key_not_private}
      true -> {:error, :unsupported_key_format}
    end
  end

  defp decode_openssh_v1(key) do
    case openssh_v1_header(key) do
      {:ok, "none", "none"} ->
        openssh_v1_private(key)

      {:ok, _cipher, _kdf} ->
        {:error, :encrypted_openssh_key}

      # A header we cannot read is not a key we cannot use: hand it to OTP anyway, which
      # decodes the body with the more forgiving `base64:mime_decode/1` (ssh_file.erl:1342).
      # Refusing here on the strength of our own stricter parse is the one way this branch
      # could reject a key that used to work.
      :error ->
        openssh_v1_private(key)
    end
  end

  defp openssh_v1_private(key) do
    case :ssh_file.decode(key, :openssh_key_v1) do
      entries when is_list(entries) ->
        case Enum.find(entries, &private_key_entry?/1) do
          {private_key, _attrs} -> {:ok, private_key}
          nil -> {:error, :no_private_key}
        end

      {:error, _reason} ->
        {:error, :key_decode_failed}
    end
  catch
    # OTP's decoders signal with `error` here and with `throw` in the PEM helpers they share;
    # both mean the same thing to us, and neither may escape into a connect attempt.
    _kind, _reason -> {:error, :key_decode_failed}
  end

  defp private_key_entry?({key, _attrs}) when is_tuple(key) and tuple_size(key) > 0,
    do: elem(key, 0) in @private_key_records

  defp private_key_entry?(_entry), do: false

  # Read the cipher and KDF names out of the key's own header (OpenSSH PROTOCOL.key:
  # "openssh-key-v1\\0" || string ciphername || string kdfname || …). `:ssh_file` gives us no
  # way to tell "encrypted" from "corrupt" — both surface as `{error, key_decode_failed}`
  # from `decode_ssh_file/4`'s catch-all (ssh_file.erl:1160-1162) — and the PEM entry is
  # tagged `not_encrypted` even for a bcrypt-protected key, so the header is the only source.
  defp openssh_v1_header(key) do
    with [_prologue, rest] <- String.split(key, @openssh_begin, parts: 2),
         [body | _epilogue] <- String.split(rest, @openssh_end, parts: 2),
         {:ok, blob} <- Base.decode64(body, ignore: :whitespace),
         <<"openssh-key-v1", 0, fields::binary>> <- blob,
         {:ok, cipher, fields} <- ssh_string(fields),
         {:ok, kdf, _fields} <- ssh_string(fields) do
      {:ok, cipher, kdf}
    else
      _ -> :error
    end
  end

  defp ssh_string(<<length::unsigned-big-32, value::binary-size(length), rest::binary>>),
    do: {:ok, value, rest}

  defp ssh_string(_bin), do: :error

  defp decode_pem(key, passphrase) do
    case :public_key.pem_decode(key) do
      [] ->
        {:error, :unsupported_key_format}

      entries ->
        case Enum.find(entries, &private_pem_entry?/1) do
          nil -> {:error, :no_private_key}
          entry -> decode_pem_entry(entry, passphrase)
        end
    end
  catch
    _kind, _reason -> {:error, :key_decode_failed}
  end

  # `decode_pem/2` with no passphrase reports `:passphrase_required` for an encrypted key,
  # which is a runtime concern rather than a format defect — see `check_format/1`.
  defp check_pem_format(key) do
    case decode_pem(key, nil) do
      {:error, :passphrase_required} -> :ok
      result -> result
    end
  end

  defp private_pem_entry?({type, _der, _cipher_info}), do: type in @private_pem_types
  defp private_pem_entry?(_entry), do: false

  defp decode_pem_entry({_type, _der, :not_encrypted} = entry, _passphrase),
    do: {:ok, :public_key.pem_entry_decode(entry)}

  # Anything else in the third element is cipher parameters: traditional PEM carries
  # `{Cipher, Salt}` (pubkey_pem.erl:143-149), PKCS#8 `{Cipher, PBES2-params}`
  # (pubkey_pem.erl:161-166). Both need the passphrase, and OTP raises `function_clause` when
  # it is missing — naming it beats that.
  defp decode_pem_entry(entry, passphrase) do
    if blank?(passphrase) do
      {:error, :passphrase_required}
    else
      {:ok, :public_key.pem_entry_decode(entry, String.to_charlist(passphrase))}
    end
  rescue
    _ -> {:error, :key_decrypt_failed}
  end

  defp blank?(value) when is_binary(value), do: String.trim(value) == ""
  defp blank?(_value), do: true

  defp drop_key({:ok, _private_key}), do: :ok
  defp drop_key(:ok), do: :ok
  defp drop_key({:error, reason}), do: {:error, reason}
end
